---
abstract: 'The invader comes from the bottom of the sea!'
author:
  - 'Naoki Tomita <tomita@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Acme::Ikamusume
name: Acme-Ikamusume
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Carp: 0
  Class::Trigger: 0
  Encode: 0
  File::ShareDir: 0
  Filter::Util::Call: 0
  Lingua::JA::Kana: 0
  Text::MeCab: 0
  perl: 5.8.1
resources:
  bugtracker: http://github.com/tomi-ru/Acme-Ikamusume/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/tomi-ru/Acme-Ikamusume
version: 0.06
